name: clova_invoice_scanner
description: CLOVA AI Invoice Scanner Mobile App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  
  # Navigation
  go_router: ^14.2.7
  
  # Network
  dio: ^5.7.0
  retrofit: ^4.4.1
  json_annotation: ^4.9.0
  
  # Camera & Image
  camera: ^0.10.6
  image_picker: ^1.1.2
  flutter_image_compress: ^2.1.0
  
  # Location
  geolocator: ^13.0.1
  permission_handler: ^11.3.1
  
  # UI
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  flutter_svg: ^2.0.10+1
  
  # Utilities
  freezed_annotation: ^2.4.4
  get_it: ^8.0.0
  dartz: ^0.10.1
  intl: ^0.19.0
  url_launcher: ^6.2.5
  share_plus: ^8.1.0
  path_provider: ^2.1.4

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.12
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  retrofit_generator: ^8.2.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
  
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300